In [1]:
import pandas as pd
import numpy as np
import keras

Using TensorFlow backend.

In [8]:
data = pd.read_csv('./data/weather/v3/2013/merged/merged_2013_h0.csv', index_col = 'Time')

In [9]:
data.head()

,temperature-002,cloudiness-002,temperature-005,cloudiness-005,temperature-015,cloudiness-015,temperature-027,cloudiness-027,temperature-070,cloudiness-070,...,temperature-645,cloudiness-645,temperature-650,cloudiness-650,temperature-675,cloudiness-675,temperature-690,cloudiness-690,temperature-747,cloudiness-747
Time,,,,,,,,,,,,,,,,,,,,,
2013-01-01 00:00:00,9.3,8,8.5,8.0,8.3,8.0,9.2,8,7.8,8,...,7.1,7,10.2,5,2.0,4,6.0,0,4.9,4
2013-01-01 01:00:00,9.4,8,8.5,8.0,8.1,8.0,9.3,7,7.4,8,...,7.1,7,10.0,3,2.2,3,5.9,1,5.6,5
2013-01-01 02:00:00,9.7,8,8.2,8.0,8.2,8.0,8.9,7,7.3,7,...,7.4,8,10.4,4,2.1,3,5.5,3,6.2,3
2013-01-01 03:00:00,8.9,8,8.2,8.0,8.1,8.0,9.1,6,7.4,7,...,7.6,6,11.0,5,3.2,3,5.2,3,4.4,4
2013-01-01 04:00:00,9.5,7,8.6,8.0,8.2,8.0,8.9,6,7.3,8,...,8.0,7,10.1,5,2.8,3,5.2,3,6.5,4