In [1]:
import pandas as pd
import glob, os
from tqdm import tqdm
directory = "./2017/" 
os.chdir(directory)
#print(glob.glob("*csv"))

In [2]:
all_files = glob.glob("*csv")

In [3]:
all_files[0]

'P4503501.201701071300 .csv'

In [4]:
len(all_files)

3096

In [5]:
error_files = []

In [6]:
merged = pd.DataFrame()

In [7]:
for file in tqdm(all_files):
    try: 
        data1 = pd.read_csv(file)
        data1 = data1.loc[data1.index[5]:data1.index[5]]        
        merged = pd.concat([merged, data1])
    except:
        print('Error with file: ' +  file)
        error_files.append(file)

100%|██████████| 3096/3096 [01:27<00:00, 35.62it/s]

In [8]:
merged.head()

,Time,temperature-002,cloudiness-002,temperature-005,cloudiness-005,temperature-015,cloudiness-015,temperature-027,cloudiness-027,temperature-070,...,temperature-645,cloudiness-645,temperature-650,cloudiness-650,temperature-675,cloudiness-675,temperature-690,cloudiness-690,temperature-747,cloudiness-747
5,2017-01-07 13:00:00,6.4,8,4.3,8,0.3,8,6.5,8,-1.1,...,6.4,0,7.1,0,7.6,7,10.6,3,15.0,0
5,2017-03-01 17:00:00,6.9,7,10.7,8,6.7,7,10.6,7,8.3,...,12.8,5,12.4,6,14.1,2,15.0,3,14.8,2
5,2017-02-13 04:00:00,4.7,3,4.4,3,2.5,0,7.0,6,-0.5,...,12.9,6,14.7,7,13.2,4,14.5,7,12.7,6
5,2017-03-02 10:00:00,8.0,0,9.4,3,9.5,3,9.0,1,9.4,...,16.2,1,13.8,1,16.6,0,14.3,0,16.1,2
5,2017-01-10 06:00:00,5.6,6,4.2,4,2.4,4,5.7,2,0.6,...,1.8,5,3.6,6,3.0,2,7.1,4,9.9,7

In [9]:
merged = merged.sort_values(by = 'Time')

In [10]:
merged.head()

,Time,temperature-002,cloudiness-002,temperature-005,cloudiness-005,temperature-015,cloudiness-015,temperature-027,cloudiness-027,temperature-070,...,temperature-645,cloudiness-645,temperature-650,cloudiness-650,temperature-675,cloudiness-675,temperature-690,cloudiness-690,temperature-747,cloudiness-747
5,2017-01-01 00:00:00,0.7,8,-3.9,4,-3.1,8,-5.0,4,-4.0,...,1.7,5,2.4,1,5.3,0,6.0,0,4.1,0
5,2017-01-01 01:00:00,0.5,8,-4.3,4,-3.2,8,-3.5,6,-4.1,...,0.8,4,3.1,3,5.8,0,5.8,0,2.8,0
5,2017-01-01 02:00:00,0.2,8,-4.8,3,-3.2,8,-2.6,7,-4.4,...,0.5,6,2.8,2,1.6,0,5.5,0,2.9,0
5,2017-01-01 03:00:00,-0.1,8,-5.1,3,-3.0,8,-3.2,5,-4.3,...,2.0,7,3.8,5,0.2,0,5.4,0,3.0,0
5,2017-01-01 04:00:00,-0.7,7,-5.3,4,-3.2,8,-2.9,4,-4.4,...,1.2,6,3.7,6,-0.5,0,5.2,0,2.3,0

In [11]:
merged.index = merged['Time']

In [12]:
len(error_files)

0

In [13]:
#len(error_files) / len(all_files)* 100

In [14]:
#error_files[0]

In [15]:
#error_files

In [16]:
merged.head()

,Time,temperature-002,cloudiness-002,temperature-005,cloudiness-005,temperature-015,cloudiness-015,temperature-027,cloudiness-027,temperature-070,...,temperature-645,cloudiness-645,temperature-650,cloudiness-650,temperature-675,cloudiness-675,temperature-690,cloudiness-690,temperature-747,cloudiness-747
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-01 00:00:00,2017-01-01 00:00:00,0.7,8,-3.9,4,-3.1,8,-5.0,4,-4.0,...,1.7,5,2.4,1,5.3,0,6.0,0,4.1,0
2017-01-01 01:00:00,2017-01-01 01:00:00,0.5,8,-4.3,4,-3.2,8,-3.5,6,-4.1,...,0.8,4,3.1,3,5.8,0,5.8,0,2.8,0
2017-01-01 02:00:00,2017-01-01 02:00:00,0.2,8,-4.8,3,-3.2,8,-2.6,7,-4.4,...,0.5,6,2.8,2,1.6,0,5.5,0,2.9,0
2017-01-01 03:00:00,2017-01-01 03:00:00,-0.1,8,-5.1,3,-3.0,8,-3.2,5,-4.3,...,2.0,7,3.8,5,0.2,0,5.4,0,3.0,0
2017-01-01 04:00:00,2017-01-01 04:00:00,-0.7,7,-5.3,4,-3.2,8,-2.9,4,-4.4,...,1.2,6,3.7,6,-0.5,0,5.2,0,2.3,0

In [17]:
del merged['Time']

In [18]:
merged.head()

,temperature-002,cloudiness-002,temperature-005,cloudiness-005,temperature-015,cloudiness-015,temperature-027,cloudiness-027,temperature-070,cloudiness-070,...,temperature-645,cloudiness-645,temperature-650,cloudiness-650,temperature-675,cloudiness-675,temperature-690,cloudiness-690,temperature-747,cloudiness-747
Time,,,,,,,,,,,,,,,,,,,,,
2017-01-01 00:00:00,0.7,8,-3.9,4,-3.1,8,-5.0,4,-4.0,7.0,...,1.7,5,2.4,1,5.3,0,6.0,0,4.1,0
2017-01-01 01:00:00,0.5,8,-4.3,4,-3.2,8,-3.5,6,-4.1,8.0,...,0.8,4,3.1,3,5.8,0,5.8,0,2.8,0
2017-01-01 02:00:00,0.2,8,-4.8,3,-3.2,8,-2.6,7,-4.4,8.0,...,0.5,6,2.8,2,1.6,0,5.5,0,2.9,0
2017-01-01 03:00:00,-0.1,8,-5.1,3,-3.0,8,-3.2,5,-4.3,8.0,...,2.0,7,3.8,5,0.2,0,5.4,0,3.0,0
2017-01-01 04:00:00,-0.7,7,-5.3,4,-3.2,8,-2.9,4,-4.4,7.0,...,1.2,6,3.7,6,-0.5,0,5.2,0,2.3,0

In [19]:
merged.to_csv('merged_17.csv')